In [1]:
import torch

# Torch Tensors

In [2]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-0.0970, -1.6282,  1.7913,  0.2255],
         [-1.0036, -0.4194,  0.8661,  1.1849],
         [-0.3000,  1.6803,  0.0722, -0.6205]],

        [[-1.0692, -1.0832, -1.5723, -0.0519],
         [ 1.0985,  1.9099,  0.2685, -0.5059],
         [ 0.2825,  1.6958,  0.1030,  1.2679]]])
tensor([[-0.0970, -1.6282,  1.7913,  0.2255, -1.0036, -0.4194,  0.8661,  1.1849,
         -0.3000,  1.6803,  0.0722, -0.6205],
        [-1.0692, -1.0832, -1.5723, -0.0519,  1.0985,  1.9099,  0.2685, -0.5059,
          0.2825,  1.6958,  0.1030,  1.2679]])
tensor([[-0.0970, -1.6282,  1.7913,  0.2255, -1.0036

In [15]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.4885, 0.8209, 0.1480, 0.6687],
        [0.3363, 0.3223, 0.2099, 0.5057],
        [0.7527, 0.4537, 0.6112, 0.9612],
        [0.0358, 0.6922, 0.4690, 0.7921]])


In [16]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 1.5299,  0.6222,  0.3271,  0.4072],
        [-1.1280,  1.6200,  0.3109, -0.1194],
        [ 0.7663,  1.5731, -0.7022,  0.0443],
        [ 1.4615,  0.2551, -0.3085, -1.4012]])
torch.float32


In [17]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([7, 6, 7, 9, 7])
torch.int64


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 7, 7],
        [6, 8, 7],
        [8, 8, 6]])


In [19]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [20]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[-0.0979, -0.1975,  0.3350, -1.1924],
        [ 0.0315, -0.0606, -0.5008,  1.0290],
        [-0.2208, -1.0395, -0.1124, -0.7847],
        [ 0.4116,  0.2896, -1.2803,  0.0191]], dtype=torch.float64)


In [22]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 2.0184,  1.4430,  0.4750,  1.0759],
        [-0.7917,  1.9423,  0.5208,  0.3863],
        [ 1.5190,  2.0268, -0.0910,  1.0055],
        [ 1.4973,  0.9473,  0.1605, -0.6091]])


In [23]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[ 2.0184,  1.4430,  0.4750,  1.0759],
        [-0.7917,  1.9423,  0.5208,  0.3863],
        [ 1.5190,  2.0268, -0.0910,  1.0055],
        [ 1.4973,  0.9473,  0.1605, -0.6091]])


In [24]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([1.4430, 1.9423, 2.0268, 0.9473])
tensor([[ 2.0184,  1.4430],
        [-0.7917,  1.9423],
        [ 1.5190,  2.0268],
        [ 1.4973,  0.9473]])
tensor([[ 2.0184,  1.4430,  0.4750,  1.0759],
        [-0.7917,  1.9423,  0.5208,  0.3863],
        [ 1.5190,  2.0268, -0.0910,  1.0055]])
tensor(1.0055)
1.0054898262023926
tensor([ 1.5190,  2.0268, -0.0910,  1.0055])


## Numpy Bridge

In [25]:
import numpy as np

In [26]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[ 2.0184,  1.4430,  0.4750,  1.0759],
        [-0.7917,  1.9423,  0.5208,  0.3863],
        [ 1.5190,  2.0268, -0.0910,  1.0055],
        [ 1.4973,  0.9473,  0.1605, -0.6091]], device='cuda:0')


In [29]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[ 2.0184,  1.4430,  0.4750,  1.0759],
        [-0.7917,  1.9423,  0.5208,  0.3863],
        [ 1.5190,  2.0268, -0.0910,  1.0055],
        [ 1.4973,  0.9473,  0.1605, -0.6091]], device='cuda:0')


In [30]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [31]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [32]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 1.4319, -1.0920, -0.5552, -0.0925, -0.0876],
        [-0.6496,  0.6209, -1.3455, -1.1079,  0.4936]])
tensor([[-2.0206, -0.2607, -0.2615,  0.6735,  0.1913],
        [ 1.0092,  0.3271,  1.1115, -0.1068,  0.4334],
        [-0.5495,  0.5357,  2.3135,  0.5528, -1.5736]])


tensor([[ 1.4319, -1.0920, -0.5552, -0.0925, -0.0876],
        [-0.6496,  0.6209, -1.3455, -1.1079,  0.4936],
        [-2.0206, -0.2607, -0.2615,  0.6735,  0.1913],
        [ 1.0092,  0.3271,  1.1115, -0.1068,  0.4334],
        [-0.5495,  0.5357,  2.3135,  0.5528, -1.5736]])


tensor([[ 1.8243,  0.2265, -2.0642],
        [-0.1659,  0.3688, -0.2429]])
tensor([[ 0.6051,  0.6340,  0.1320,  0.1664,  0.1265],
        [ 0.0506,  0.2609,  1.3696, -0.2370,  0.8723]])


tensor([[ 1.8243,  0.2265, -2.0642,  0.6051,  0.6340,  0.1320,  0.1664,  0.1265],
        [-0.1659,  0.3688, -0.2429,  0.0506,  0.2609,  1.3696, -0.2370,  0.8723]])




## Adding Dimensions to Tensors

In [33]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.1529, 0.4772, 0.4501, 0.7971],
         [0.6097, 0.1403, 0.0473, 0.3478],
         [0.9360, 0.5698, 0.0746, 0.6267]],

        [[0.7016, 0.1112, 0.7968, 0.7945],
         [0.3163, 0.0556, 0.9019, 0.2668],
         [0.3334, 0.6855, 0.0143, 0.9456]]])


tensor([[0.4501, 0.0473, 0.0746],
        [0.7968, 0.9019, 0.0143]])
torch.Size([2, 3])


tensor([[[0.4501],
         [0.0473],
         [0.0746]],

        [[0.7968],
         [0.9019],
         [0.0143]]])
torch.Size([2, 3, 1])


## AutoGrad

In [34]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [35]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [36]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [37]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [38]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
